DROP TABLE IF EXISTS img_data CASCADE;
DROP TABLE IF EXISTS video_data CASCADE;

CREATE TABLE img_data(
    img_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img_title text NOT NULL,
    img_data bytea NOT NULL,
    img_type text NOT NULL
);
CREATE TABLE video_data(
    video_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_title text NOT NULL,
    video_data bytea NOT NULL,
    video_type text NOT NULL
);