DROP TABLE IF EXISTS img_data CASCADE;
DROP TABLE IF EXISTS video_data CASCADE;

CREATE TABLE img_data(
    img_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img_title text,
    img_data bytea,
    img_type text
);
CREATE TABLE video_data(
    id_video int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    video_data bytea,
    type text
);