DROP TABLE IF EXISTS data CASCADE;


CREATE TABLE data(
    id_data int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un_text text
);


INSERT INTO data (un_text) VALUES ('Bonjour de la base de données :)');